name: main

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  NODE_VERSION: "18.x"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm run build-storybook
      - run: npm run lint
      - run: npm run lint:e2e
      - run: npm run test -- --coverage
      - uses: cypress-io/github-action@v5
        with:
          start: npm run start
      - uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
